services:
  pg:
    container_name: mircoservice-pg
    image: docker.io/postgres:latest
    restart: always
    ports:
      - 5123:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data